    EVALUATE
	SUMMARIZE(
        FILTER(
            fCarteira,
            RELATED(dNotas[ChaveNotaFiscal]) <> BLANK()
        ),
        fCarteira[CnpjCpfCedente],
        "TotalCedente", [Total da Carteira]
    )